# frozen_string_literal: true

source "https://rubygems.org/"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'colorize', '~> 0.8.1'
gem 'tty-platform', '~> 0.3.0'
gem 'ipaddr', '~> 1.2', '>= 1.2.2'
gem 'macaddr', '~> 1.7', '>= 1.7.2'
gem 'uri', '~> 0.10.0'
gem 'http', '~> 4.4'
gem 'net', '~> 0.3.3'
gem 'json', '~> 2.3'